# -*- coding: utf-8 -*-
"""Random_Forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZzZ_fSBccvHORsaAqhxV-jmhm8L4mDk4
"""

import numpy as np
import pandas as pd
import seaborn as sns
import sklearn

from sklearn.datasets import load_iris

iris=load_iris()
iris.target_names
iris.feature_names

data=pd.DataFrame(iris.data,columns=iris.feature_names)
data

data['species']=iris.target

X=data.iloc[:,:-1]
y=data.iloc[:,-1]

X

y

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

from sklearn.ensemble import RandomForestClassifier
dt=RandomForestClassifier(n_estimators=100,criterion='gini')
dt.fit(x_train,y_train)
predictions=dt.predict(x_test)

dt.score(x_test,y_test)

dt.predict([[5.1,3.5,1.4,0.2]])

predictions

import scipy

from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,predictions)

mse

sns.pairplot(data,hue='species')

